### ISSUE TITLE
错误: 找不到或无法加载主类 FPSMaster.jar

### ISSUE THREAD

**Issue by HIMWLWDSJ** [SuperSkidder/FPSMasterOpenSourceProject#1]
`>java FPSMaster.jar                                                                                                             
错误: 找不到或无法加载主类 FPSMaster.jar
原因: java.lang.ClassNotFoundException: FPSMaster.jar`

OS: archlinux x86_64
JVM: zulu 17.34.19-ca-jre17.0.3-linux_x64
linux 版本: 6.4.9.arch1-1
FPSMaster 版本: FPSMaster v3 1.12.2
显示服务器: X11

我试过OpenJDK，它也有这个错误

**Comment by SuperSkidder** [comment]
客户端不是这么启动的。
建议你先去学学java基础
